# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: '{{ cookiecutter.python_version }}'

# How to install the project.  We need to specify to use `pip`, because 
# otherwise RTD may try to directly execute `setup.py`, which doesn't exist.
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc

